AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.server.handler
      Runtime: python3.10
      Timeout: 30
      CodeUri: .
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ENV: "local"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
